### ISSUE TITLE
Problems with Home Assistant 2024.01.0b

### ISSUE THREAD

**Issue by guevara777** [pail23/stiebel_eltron_isg_component#166]
## Version of the custom_component
2023.10.2

## Configuration

```yaml
Setup via UI.
```

## Describe the bug
Some of the sensors that measure values (like temperature or energy) have no value due to problems with the device_class (see following log entries).

## Debug log

```text

Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:360
Integration: Sensor (documentation, issues)
First occurred: 10:22:52 (3 occurrences)
Last logged: 10:34:32

Error while setting up stiebel_eltron_isg platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 360, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/stiebel_eltron_isg/sensor.py", line 365, in async_setup_entry
    description.state_class = STATE_CLASS_TOTAL_INCREASING
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 4, in __setattr__
dataclasses.FrozenInstanceError: cannot assign to field 'state_class'

------

Logger: homeassistant.components.group.sensor
Source: components/group/sensor.py:331
Integration: Gruppe (documentation, issues)
First occurred: 10:23:39 (16 occurrences)
Last logged: 10:33:43

Unable to use state. Only numerical states are supported, entity sensor.stiebel_eltron_isg_altbau_consumed_water_heating_today with value unavailable excluded from calculation
Unable to use state. Only numerical states are supported, entity sensor.stiebel_eltron_isg_produced_heating_today with value unavailable excluded from calculation
Unable to use state. Only numerical states are supported, entity sensor.stiebel_eltron_isg_produced_water_heating_today with value unavailable excluded from calculation
Unable to use state. Only numerical states are supported, entity sensor.stiebel_eltron_isg_altbau_produced_heating_today with value unavailable excluded from calculation
Unable to use state. Only numerical states are supported, entity sensor.stiebel_eltron_isg_altbau_produced_water_heating_today with value unavailable excluded from calculation

--------

Logger: homeassistant.const
Source: helpers/deprecation.py:204
First occurred: 10:22:48 (6 occurrences)
Last logged: 10:23:21

IRRADIATION_WATTS_PER_SQUARE_METER was used from fusion_solar, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfIrradiance.WATTS_PER_SQUARE_METER instead, please create a bug report at https://github.com/tijsverkoyen/HomeAssistant-FusionSolar/issues
DEVICE_CLASS_ENERGY was used from stiebel_eltron_isg, this is a deprecated constant which will be removed in HA Core 2025.1. Use SensorDeviceClass.ENERGY instead, please create a bug report at https://github.com/pail23/stiebel_eltron_isg_component/issues
ENERGY_KILO_WATT_HOUR was used from stiebel_eltron_isg, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfEnergy.KILO_WATT_HOUR instead, please create a bug report at https://github.com/pail23/stiebel_eltron_isg_component/issues
ENERGY_KILO_WATT_HOUR was used from huawei_solar, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfEnergy.KILO_WATT_HOUR instead, please create a bug report at https://github.com/wlcrs/huawei_solar/issues
POWER_WATT was used from huawei_solar, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfPower.WATT instead, please create a bug report at https://github.com/wlcrs/huawei_solar/issues

--------

Logger: homeassistant.components.sensor
Source: helpers/deprecation.py:204
Integration: Sensor (documentation, issues)
First occurred: 10:22:49 (4 occurrences)
Last logged: 10:22:49

STATE_CLASS_MEASUREMENT was used from stiebel_eltron_isg, this is a deprecated constant which will be removed in HA Core 2025.1. Use SensorStateClass.MEASUREMENT instead, please create a bug report at https://github.com/pail23/stiebel_eltron_isg_component/issues
STATE_CLASS_TOTAL_INCREASING was used from stiebel_eltron_isg, this is a deprecated constant which will be removed in HA Core 2025.1. Use SensorStateClass.TOTAL_INCREASING instead, please create a bug report at https://github.com/pail23/stiebel_eltron_isg_component/issues

```

**Comment by guevara777** [comment]
Problem is still there with 2024.01.0b4

![image](https://github.com/pail23/stiebel_eltron_isg_component/assets/29648553/f7e5bb3d-5d2b-49a2-8ff8-ee4d7e330549)

**Comment by pail23** [comment]
Should be fixed in the release 2024.1 of this integration.

**Comment by guevara777** [comment]
Sadly i can´t confirm it is fixed. Still having the same Problem with Core 2024.1.0b8 and 2024.1 of the Integration.

![image](https://github.com/pail23/stiebel_eltron_isg_component/assets/29648553/ac9d6a04-e613-4995-aab9-995b878891db)

This is what i see in the Logs:
```
Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:360
Integration: Sensor (documentation, issues)
First occurred: 18:36:00 (3 occurrences)
Last logged: 18:59:34

Error while setting up stiebel_eltron_isg platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 360, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/stiebel_eltron_isg/sensor.py", line 382, in async_setup_entry
    description.state_class = SensorStateClass.TOTAL_INCREASING
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 4, in __setattr__
dataclasses.FrozenInstanceError: cannot assign to field 'state_class'

```

**Comment by guevara777** [comment]
Anything i can do to help?

**Comment by pail23** [comment]
I gave it another try and created 2024.1.1.

Does it work now?

**Comment by guevara777** [comment]
Yes, it works now. Thank you so much! 🥇 

![image](https://github.com/pail23/stiebel_eltron_isg_component/assets/29648553/f6564e92-de4f-49aa-8888-4f750f0fca74)
